name: Trigger auto deployment for ca-fabric-rti-mcp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-fabric-rti-mcp-AutoDeployTrigger-34b76ddc-f7ad-469c-9d6f-3f8e2a9f02e8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAFABRICRTIMCP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAFABRICRTIMCP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAFABRICRTIMCP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.CAFABRICRTIMCP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAFABRICRTIMCP_REGISTRY_PASSWORD }}
          containerAppName: ca-fabric-rti-mcp
          resourceGroup: rg-fabricagent
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


